pipeline:

  build:
    image: quay.io/ukhomeofficedigital/drone-docker
    commands:
      - docker build -t ref-data-gov-tool-prototype:$${DRONE_COMMIT_SHA} .
    when:
      event: push

  image_to_quay:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
      - DOCKER_USERNAME
      - DOCKER_PASSWORD
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/ref-data-gov-tool-prototype
    tags:
      - ${DRONE_BUILD_NUMBER}
      - ${DRONE_COMMIT_SHA}
      - latest
    when:
      branch: master
      event: [ push, deployment ]

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - DEV_HOSTNAME
      - DEV_KUBE_NAMESPACE
      - DEV_KUBE_SERVER
      - DEV_KUBE_TOKEN
    commands:
      - export HOSTNAME=$${DEV_HOSTNAME}
      - export KUBE_NAMESPACE=$${DEV_KUBE_NAMESPACE}
      - export KUBE_SERVER=$${DEV_KUBE_SERVER}
      - export KUBE_TOKEN=$${DEV_KUBE_TOKEN}
      - kd --insecure-skip-tls-verify -f kube/deployment.yml -f kube/service.yml -f kube/ingress.yml -f kube/network-policy.yml
    when:
      branch: master
      event: [ push, deployment ]

  deploy_to_prod:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - PROD_HOSTNAME
      - PROD_KUBE_NAMESPACE
      - PROD_KUBE_SERVER
      - PROD_KUBE_TOKEN
    commands:
      - export HOSTNAME=$${PROD_HOSTNAME}
      - export KUBE_NAMESPACE=$${PROD_KUBE_NAMESPACE}
      - export KUBE_SERVER=$${PROD_KUBE_SERVER}
      - export KUBE_TOKEN=$${PROD_KUBE_TOKEN}
      - kd --insecure-skip-tls-verify -f kube/deployment.yml -f kube/service.yml -f kube/ingress.yml -f kube/network-policy.yml
    when:
      event: deployment
      environment: production
