pipeline:

  synch_dev_secrets:
    image: quay.io/ukhomeofficedigital/cop-secrets
    environment:
      - DRONE_SERVER=https://drone.acp.homeoffice.gov.uk
      - DEPLOY_ENV=dev
    secrets:
      - source: DEV_DRONE_AWS_ACCESS_KEY_ID
        target: AWS_ACCESS_KEY_ID
      - source: DEV_DRONE_AWS_SECRET_ACCESS_KEY
        target: AWS_SECRET_ACCESS_KEY
      - source: DRONE_PUBLIC_TOKEN
        target: DRONE_TOKEN
    when:
      environment: secrets
      event: deployment

  synch_production_secrets:
    image: quay.io/ukhomeofficedigital/cop-secrets
    environment:
      - DRONE_SERVER=https://drone.acp.homeoffice.gov.uk
      - DEPLOY_ENV=production
    secrets:
      - source: PRODUCTION_DRONE_AWS_ACCESS_KEY_ID
        target: AWS_ACCESS_KEY_ID
      - source: PRODUCTION_DRONE_AWS_SECRET_ACCESS_KEY
        target: AWS_SECRET_ACCESS_KEY
      - source: DRONE_PUBLIC_TOKEN
        target: DRONE_TOKEN
    when:
      environment: secrets
      event: deployment

  build:
    image: quay.io/ukhomeofficedigital/drone-docker
    commands:
      - docker build -t ref-data-gov-tool-prototype:$${DRONE_COMMIT_SHA} .
    when:
      event: push

  image_to_quay:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
    - source: QUAY_USERNAME
      target: DOCKER_USERNAME
    - source: QUAY_PASSWORD
      target: DOCKER_PASSWORD
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/ref-data-gov-tool-prototype
    tags: ${DRONE_COMMIT_SHA}
    when:
      branch: master
      event: [ push, deployment ]

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
    - source: DEV_REFDATA_PROTOTYPE_URL
      target: REFDATA_PROTOTYPE_URL
    - source: DEV_KUBE_NAMESPACE_COP_PROTOTYPE
      target: KUBE_NAMESPACE
    - source: DEV_KUBE_SERVER
      target: KUBE_SERVER
    - source: DEV_PROTOTYPE_KUBE_TOKEN
      target: KUBE_TOKEN
    commands:
      - export REFDATA_PROTOTYPE_NAME="ref-data-gov-tool-prototype"
      - kd --insecure-skip-tls-verify -f kube/deployment.yml -f kube/service.yml -f kube/ingress.yml -f kube/network-policy.yml
    when:
      branch: master
      event: [ push, deployment ]

  deploy_to_prod:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
    - source: PRODUCTION_REFDATA_PROTOTYPE_URL
      target: REFDATA_PROTOTYPE_URL
    - source: PRODUCTION_KUBE_NAMESPACE_COP_PROTOTYPE
      target: KUBE_NAMESPACE
    - source: PRODUCTION_KUBE_SERVER
      target: KUBE_SERVER
    - source: PRODUCTION_PROTOTYPE_KUBE_TOKEN
      target: KUBE_TOKEN
    commands:
      - export REFDATA_PROTOTYPE_NAME="ref-data-gov-tool-prototype"
      - kd --insecure-skip-tls-verify -f kube/deployment.yml -f kube/service.yml -f kube/ingress.yml -f kube/network-policy.yml
    when:
      event: deployment
      environment: production

  notify:
    image: plugins/slack
    secrets: [ SLACK_WEBHOOK ]
    channel: cop-deployments
    username: Drone Build Watcher
    template: >
      {{#build.deployTo}}
        *{{repo.name}} - Build {{build.number}} - {{uppercasefirst build.deployTo}} - {{uppercase build.status}}*
      {{else}}
        *{{repo.name}} - Build {{build.number}} - Development - {{uppercase build.status}}*
      {{/build.deployTo}}
      {{build.link}}
    when:
      branch: master
      event: [ push, deployment ]
      status: [ success, failure ]
