---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ref-data-gov-tool-prototype
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      name: ref-data-gov-tool-prototype
  template:
    metadata:
      labels:
        name: ref-data-gov-tool-prototype
    spec:
      containers:
      - name: prototype
        image: quay.io/ukhomeofficedigital/ref-data-gov-tool-prototype:{{.DRONE_COMMIT_SHA}}
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 500Mi
        ports:
          - name: prototype
            containerPort: 3000

      - name: proxy
        image: quay.io/ukhomeofficedigital/nginx-proxy
        securityContext:
          runAsNonRoot: true
        env:
          - name: PROXY_SERVICE_HOST
            value: 'http://127.0.0.1'
          - name: PROXY_SERVICE_PORT
            value: '3000'
          - name: LOG_FORMAT_NAME
            value: 'json'
          - name: NAXSI_USE_DEFAULT_RULES
            value: 'FALSE'
        ports:
          - name: https
            containerPort: 10443
