---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ref-data-gov-tool-prototype-ingress
  labels:
    stable.k8s.psg.io/kcm.class: default
  annotations:
    kubernetes.io/ingress.class: "nginx-external"
    ingress.kubernetes.io/backend-protocol: "HTTPS"
    stable.k8s.psg.io/kcm.provider: http
spec:
  rules:
  - host: {{.REFDATA_PROTOTYPE_URL}}
    http:
      paths:
      - backend:
          serviceName: ref-data-gov-tool-prototype-service
          servicePort: 10443
        path: /
  tls:
  - hosts:
    - {{.REFDATA_PROTOTYPE_URL}}
    secretName: ref-data-gov-tool-prototype-tls
