---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ref-data-gov-tool-prototype-ingress
  labels:
    cert-manager.io/solver: http01
  annotations:
    cert-manager.io/enabled: "true"
    kubernetes.io/ingress.class: "nginx-external"
    ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  rules:
  - host: {{.REFDATA_PROTOTYPE_URL}}
    http:
      paths:
      - backend:
          serviceName: ref-data-gov-tool-prototype-service
          servicePort: 10443
        path: /
  tls:
  - hosts:
    - {{.REFDATA_PROTOTYPE_URL}}
    secretName: ref-data-gov-tool-prototype-cmio
