---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak
type: Opaque
data:
  keycloak_client_id: {{.KEYCLOAK_CLIENT_ID | b64enc}}
  keycloak_client_secret: {{.KEYCLOAK_CLIENT_SECRET | b64enc}}
  keycloak_discovery_url: {{.KEYCLOAK_DISCOVERY_URL | b64enc}}
  keycloak_encryption_key: {{.KEYCLOAK_ENCRYPTION_KEY | b64enc}}
